Made function api_search
MrRaccoonUA/upc2images pull request #2
Opened 2021-01-29 11:01 UTC by MrRaccoonUA

# **What does this pull request do?**

The function is created that takes UPCs and returns: product name, UPCs, and image links

2021-01-29 15:02 UTC, aartiukh requested changes
Please add unit tests

2021-01-30 22:59 UTC, aartiukh requested changes

2021-01-30 22:59 UTC, aartiukh commented on main.py
> +        time.sleep(10.5)
Magic number, make it configurable from function params or create a constant if it doesn't make sense,

2021-01-30 22:59 UTC, aartiukh commented on main.py
> +def api_search(df, upc_column):
Add documentation

2021-01-30 22:59 UTC, aartiukh commented on main.py
> +                print(df[df[upc_column] == code].index.values, 'Success', 'Iteration time:',
Use `logging` module instead of `print`

2021-01-30 22:59 UTC, aartiukh commented on main.py
> +                df_report = df_report.append({'Code': data['code'], 'UPC': item['ean'], 'Product Name': item['title'],
Why do we need to call `append` twice? You can put empty image url in case of failure

2021-01-30 22:59 UTC, aartiukh commented on main.py
> +        df_report['UPC'] = df_report['UPC'].apply(int)
Please elaborate, why do we need this?

2021-01-30 22:59 UTC, aartiukh commented on main.py
> +        df_report.to_csv('Report.csv')
This should be done outside this method, just return dataframe

2021-01-30 22:59 UTC, aartiukh commented on main.py
> +    df[upc_column] = df[upc_column].apply(str)
We should not do this here, move this code to `__main__`

2021-01-30 22:59 UTC, aartiukh commented on test-api-search.py
> +        expect_df = pd.read_json('Report.json')
```suggestion
        expected_df_report = pd.read_json('Report.json')
```

2021-01-30 22:59 UTC, aartiukh commented on test-api-search.py
> +        df[upc_column_name] = df[upc_column_name].apply(str)
Why do we need this?

2021-01-31 21:11 UTC, MrRaccoonUA commented on main.py
> +        time.sleep(10.5)
Fixed

2021-01-31 21:11 UTC, MrRaccoonUA commented on main.py
> +                print(df[df[upc_column] == code].index.values, 'Success', 'Iteration time:',
Done

2021-01-31 21:11 UTC, MrRaccoonUA commented on main.py
> +        df_report['UPC'] = df_report['UPC'].apply(int)
Fixed

2021-01-31 21:11 UTC, MrRaccoonUA commented on main.py
> +        df_report.to_csv('Report.csv')
Done

2021-01-31 21:11 UTC, MrRaccoonUA commented on main.py
> +    df[upc_column] = df[upc_column].apply(str)
Done

2021-01-31 21:11 UTC, MrRaccoonUA commented on test-api-search.py
> +        expect_df = pd.read_json('Report.json')
Done

2021-01-31 21:15 UTC, MrRaccoonUA commented on test-api-search.py
> +        df[upc_column_name] = df[upc_column_name].apply(str)
This is the input to the unittest function

2021-02-02 09:50 UTC, MrRaccoonUA commented on main.py
> +def api_search(df, upc_column):
Done

2021-02-05 19:03 UTC, aartiukh commented on main.py
> +    """
Can we use list here?

2021-02-05 19:06 UTC, aartiukh requested changes

2021-02-05 19:06 UTC, aartiukh commented on main.py
> +    df_report = pd.DataFrame(data={'Code': [], 'UPC': [], 'Product Name': [], 'Images links': []})
Remove code, rename to `df_report` to `df_upc_images`

2021-02-05 19:06 UTC, aartiukh commented on main.py
> +    rate_limit = 11
API_COOL_DOWN_TIMEOUT

2021-02-05 19:06 UTC, aartiukh commented on main.py
> +    df_upc[upc_column_name] = df_upc[upc_column_name].apply(str)
Use list here

2021-02-06 10:57 UTC, MrRaccoonUA commented on main.py
> +    """
Yes, we can. Done

2021-02-06 10:58 UTC, MrRaccoonUA commented on main.py
> +    df_report = pd.DataFrame(data={'Code': [], 'UPC': [], 'Product Name': [], 'Images links': []})
Done

2021-02-06 10:59 UTC, MrRaccoonUA commented on main.py
> +    rate_limit = 11
Done

2021-02-06 10:59 UTC, MrRaccoonUA commented on main.py
> +    df_upc[upc_column_name] = df_upc[upc_column_name].apply(str)
Done

2021-02-06 21:54 UTC, aartiukh requested changes

2021-02-06 21:54 UTC, aartiukh commented on main.py
> +    df_upc = load_data(csv_file_name)
Let's remove this csv file here and allow user to set the UPD list manually or read from `txt` file.

2021-02-06 21:54 UTC, aartiukh commented on main.py
> +    api_cool_down_timeout = 11
UPPER_CASE pls for constants

2021-02-08 08:44 UTC, MrRaccoonUA commented on main.py
> +    api_cool_down_timeout = 11
Fixed

2021-02-08 08:44 UTC, MrRaccoonUA commented on main.py
> +    df_upc = load_data(csv_file_name)
Done

2021-02-08 16:12 UTC, aartiukh approved these changes

2021-02-08 17:56 UTC, merged