Made function link_extractor
MrRaccoonUA/upc2images pull request #3
Opened 2021-02-09 18:00 UTC by MrRaccoonUA

**What does this pull request do?**

A function is implemented that searches for links to images and changes their resolution

2021-02-12 13:12 UTC, aartiukh commented on main.py
> +        if len(target_link) > 0 and len(link_wal) == 0:
Please add comments to this conditions

2021-02-12 13:13 UTC, aartiukh commented on main.py
> +            size = re.sub(r"1000", "3000", target_link[0])
`1000` and `3000` are magic numbers, create variables for them

2021-02-13 14:05 UTC, MrRaccoonUA commented on main.py
> +        if len(target_link) > 0 and len(link_wal) == 0:
Added

2021-02-13 14:06 UTC, MrRaccoonUA commented on main.py
> +            size = re.sub(r"1000", "3000", target_link[0])
Fixed

2021-02-14 21:00 UTC, aartiukh requested changes

2021-02-14 21:00 UTC, aartiukh commented on main.py
> +                yield item
👍  for `yield`

2021-02-14 21:43 UTC, MrRaccoonUA commented on main.py
> +            if item[:l] == prefix:
If I use `-1` here, then I will need to send all link to the function. When I use `:l` compare the beginning of each reference in the array with a prefix and if they match then I save it

2021-02-14 21:43 UTC, MrRaccoonUA commented on main.py
> +    def search(lst, prefix):
Fixed

2021-02-14 21:43 UTC, MrRaccoonUA commented on main.py
> +    target_default_size = 1000
Fixed

2021-02-14 21:44 UTC, MrRaccoonUA commented on main.py
> +        link_wal = (list(search(lst, prefix)))
Fixed

2021-02-14 21:44 UTC, MrRaccoonUA commented on main.py
> +                yield item
Thank you

2021-02-17 17:29 UTC, aartiukh requested changes

2021-02-17 17:29 UTC, aartiukh commented on main.py
> +    df_temp = pd.DataFrame(data={})
Please give `df_temp` more meaningful name

2021-02-17 17:29 UTC, aartiukh commented on main.py
> +        l = len(prefix)
Drop this var, do not use `l` as a var name, it looks like `1`

2021-02-17 17:29 UTC, aartiukh commented on main.py
> +        lst = df['Images links'][row]
Rename `lst`

2021-02-17 17:29 UTC, aartiukh commented on main.py
> +        if len(target_link) > 0 and len(link_wal) == 0:
Get rid of these ifs. Try to get target imegas first, then check if len > 0 and return df on success. On failure, try to get walmart image and again check if len > 0 ...

2021-02-18 09:12 UTC, MrRaccoonUA commented on main.py
> +        if len(target_link) > 0 and len(link_wal) == 0:
Fixed in the Refactoring

2021-02-18 09:12 UTC, MrRaccoonUA commented on main.py
> +        lst = df['Images links'][row]
Fixed in the Refactoring

2021-02-18 09:12 UTC, MrRaccoonUA commented on main.py
> +        l = len(prefix)
Fixed in the Refactoring

2021-02-18 09:13 UTC, MrRaccoonUA commented on main.py
> +    df_temp = pd.DataFrame(data={})
Fixed in the Refactoring

2021-02-18 10:13 UTC, aartiukh commented on main.py
> +    detail_doc = dict()
@MrRaccoonUA  Use named tuple instead of dict.
See https://www.accelebrate.com/blog/named-tuples-in-python for the reference

2021-02-18 13:43 UTC, MrRaccoonUA commented on main.py
> +    detail_doc = dict()
Changed

2021-02-19 20:50 UTC, aartiukh commented on main.py
> +        return None
```suggestion
    if data['code'] != 'OK':
        return None
 
    product_info = namedtuple('Product', 'UPC Product_Name Images_Links')
    for item in data['items']:
        product_info = product_info(item['ean'], item['title'], item['images'])
    return product_info
        
```

2021-02-19 20:50 UTC, aartiukh commented on main.py
> +        return one_link
add empty line

2021-02-19 20:50 UTC, aartiukh commented on main.py
> +    if target_prefix:
2 `if`s -- two functions

2021-02-21 20:29 UTC, aartiukh commented on main.py
> +    resp = requests.get('https://api.upcitemdb.com/prod/trial/lookup?upc=' + code, headers=headers)
Create a vat for this `'https://api.upcitemdb.com/prod/trial/lookup?upc='`

2021-02-21 20:31 UTC, aartiukh commented on main.py
> +            product_info = product_info(item['ean'], item['title'], item['images'])
Create a list for image links and then create a tuple

2021-02-22 20:42 UTC, MrRaccoonUA commented on main.py
> +            product_info = product_info(item['ean'], item['title'], item['images'])
Done

2021-02-22 20:42 UTC, MrRaccoonUA commented on main.py
> +    resp = requests.get('https://api.upcitemdb.com/prod/trial/lookup?upc=' + code, headers=headers)
Done

2021-02-22 20:42 UTC, MrRaccoonUA commented on main.py
> +    if target_prefix:
Done

2021-02-22 20:42 UTC, MrRaccoonUA commented on main.py
> +        return one_link
Done

2021-02-22 20:42 UTC, MrRaccoonUA commented on main.py
> +        return None
Done

2021-02-22 20:52 UTC, aartiukh approved these changes

2021-02-22 20:54 UTC, merged